"""
Pydantic request/response schemas for the ExpenseKeeper Report Service.
These define the exact API contract between the Node backend and this service.
"""

from __future__ import annotations

from typing import Literal, Optional
from pydantic import BaseModel, Field


# ─────────────────────────────────────────────────────────────────────────────
# Incoming request schemas
# ─────────────────────────────────────────────────────────────────────────────


class ReportMeta(BaseModel):
    monthKey: str                            # e.g. "2026-02"
    monthLabel: str                          # e.g. "February 2026"
    userType: str = "young_professional"
    userName: str = "User"
    monthlyBudget: float = 0.0
    timezone: str = "UTC"
    generatedAt: Optional[str] = None


class CategoryItem(BaseModel):
    name: str
    amount: float
    percent: float
    count: int = 0


class BudgetItem(BaseModel):
    name: str
    allocated: float
    spent: float
    remaining: float
    usagePercent: float = 0.0


class PeriodChange(BaseModel):
    vsLastMonth: Optional[float] = None      # % change; None = no prior data
    vsLastYear: Optional[float] = None


class NoteContext(BaseModel):
    date: str
    category: str
    amount: float
    note: str


class RecurringSignal(BaseModel):
    description: str
    category: str
    estimatedMonthlyAmount: float
    monthsDetected: int
    confidence: float


class LifestyleCreepSignal(BaseModel):
    category: str
    currentAmount: float
    baselineAmount: float
    growthPercent: float


class Metrics(BaseModel):
    totalSpent: float
    totalIncome: float = 0.0
    netSavings: float = 0.0
    budgetVariance: float = 0.0              # budget − spent (positive = under)
    budgetUsedPercent: float = 0.0           # spent / budget * 100; may exceed 100 if over budget
    budgetAdherencePercent: float = 0.0      # clamped 0–100
    periodChange: PeriodChange = Field(default_factory=PeriodChange)
    dailyAverage: float = 0.0
    transactionCount: int = 0
    categoryBreakdown: list[CategoryItem] = []
    topSpendingCategory: str = ""
    topCategoryAmount: float = 0.0
    budgetItems: list[BudgetItem] = []
    noteContexts: list[NoteContext] = []
    recurringSignals: list[RecurringSignal] = []
    recurringEstimatedTotal: float = 0.0
    lifestyleCreepSignals: list[LifestyleCreepSignal] = []
    totalLifestyleCreepPercent: Optional[float] = None
    totalLifestyleCreepExcess: float = 0.0


class TrendPoint(BaseModel):
    label: str
    amount: float


class ChartData(BaseModel):
    weeklyTrend: list[TrendPoint] = []
    dailyTrend: list[TrendPoint] = []


class GenerateReportRequest(BaseModel):
    reportMeta: ReportMeta
    metrics: Metrics
    chartData: ChartData = Field(default_factory=ChartData)


class ChatMessage(BaseModel):
    role: Literal["user", "assistant"]
    content: str = Field(min_length=1, max_length=2000)


class MonthSummary(BaseModel):
    monthKey: str
    monthLabel: str
    totalSpent: float = 0.0
    monthlyBudget: float = 0.0
    budgetVariance: float = 0.0
    topCategories: list[str] = Field(default_factory=list)


class ChatRequest(BaseModel):
    reportPayload: GenerateReportRequest
    history: list[ChatMessage] = Field(default_factory=list)
    message: str = Field(min_length=1, max_length=500)
    allMonthsSummary: list[MonthSummary] = Field(default_factory=list)


# ─────────────────────────────────────────────────────────────────────────────
# Outgoing response schemas
# ─────────────────────────────────────────────────────────────────────────────


class NarrativeOutput(BaseModel):
    """Structured narrative sections generated by the LLM (or template fallback)."""
    executive_summary: str
    spending_highlights: str
    category_analysis: list[str]
    anomalies: list[str]
    budget_insights: str
    recommendations: list[str]
    next_month_watchouts: list[str]


class ModelInfo(BaseModel):
    modelName: str
    provider: str
    usedFallback: bool


class NarrativeResponse(BaseModel):
    narrative: NarrativeOutput
    modelInfo: ModelInfo
    generatedAt: str


class ChatResponse(BaseModel):
    reply: str
    modelInfo: ModelInfo
    generatedAt: str
