# -*- coding: utf-8 -*-
"""expense_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ka56CbBrhMNS8tVHcUe8PozoN0tlWE_Y
"""

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, TimeSeriesSplit, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error
from xgboost import XGBRegressor
import joblib

df = pd.read_csv("Personal_Finance_Dataset.csv")


# -----------------------------
# Preprocessing Function
# -----------------------------
def preprocess_data(df):
    df = df.copy()
    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
    df['Type'] = df['Type'].astype(str).str.strip().str.lower()
    df = df[df['Type'] == 'expense']

    # Monthly totals per category
    monthly = (
        df.groupby([df['Date'].dt.to_period('M'), 'Category'])
        .agg(total_amount=('Amount', 'sum'))
        .reset_index()
    )
    monthly['Date'] = monthly['Date'].dt.to_timestamp()

    # Lag features
    monthly['lag_1'] = monthly.groupby('Category')['total_amount'].shift(1)
    monthly['lag_2'] = monthly.groupby('Category')['total_amount'].shift(2)
    monthly['lag_3'] = monthly.groupby('Category')['total_amount'].shift(3)

    # Rolling averages
    monthly['Rolling3'] = (
        monthly.groupby('Category')['total_amount']
        .transform(lambda x: x.shift(1).rolling(3, min_periods=1).mean())
    )
    monthly['Rolling6'] = (
        monthly.groupby('Category')['total_amount']
        .transform(lambda x: x.shift(1).rolling(6, min_periods=1).mean())
    )

    # Time features
    monthly['month_num'] = monthly['Date'].dt.month
    monthly['month_sin'] = np.sin(2*np.pi*monthly['month_num']/12)
    monthly['month_cos'] = np.cos(2*np.pi*monthly['month_num']/12)

    # Target
    monthly['target'] = monthly.groupby('Category')['total_amount'].shift(-1)

    # Clean data
    data = monthly.dropna().reset_index(drop=True)
    data = pd.get_dummies(data, columns=['Category'])

    return data

def train_model(data, model_type="xgb"):
    FEATURES = [
        'lag_1', 'lag_2', 'lag_3',
        'Rolling3', 'Rolling6',
        'month_num', 'month_sin', 'month_cos'
    ] + [col for col in data.columns if col.startswith('Category')]

    X = data[FEATURES]
    y = data['target']

    # Train/test split (last 12 months test)
    test_size = 12 if len(data) > 24 else int(0.2*len(data))
    train_X, test_X = X[:-test_size], X[-test_size:]
    train_y, test_y = y[:-test_size], y[-test_size:]

    # Choose model
    if model_type == "xgb":
        model = XGBRegressor(n_estimators=200, learning_rate=0.1, random_state=42)
    else:
        model = RandomForestRegressor(random_state=42)

    model.fit(train_X, train_y)
    preds = model.predict(test_X)

    mae = mean_absolute_error(test_y, preds)
    rmse = np.sqrt(mean_squared_error(test_y, preds))

    print(f"{model_type.upper()} Model Results")
    print("MAE:", mae)
    print("RMSE:", rmse)

    return model, FEATURES

# -----------------------------
# Save Model Function
# -----------------------------
def save_model(model, features, path="expense_forecast.pkl"):
    joblib.dump({"model": model, "features": features}, path)
    print(f"✅ Model saved at {path}")

if __name__ == "__main__":
    df = pd.read_csv("Personal_Finance_Dataset.csv")
    data = preprocess_data(df)
    model, FEATURES = train_model(data, model_type="xgb")
    save_model(model, FEATURES)